# -----------------------------------------------------------------------------
# Auteur       : TRISTAN NAULEAU 
# Date         : 2025-07-12
# Licence      : GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
#
# Ce travail est distribué librement en accord avec les termes de la
# GNU GPL v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# Vous êtes libre de redistribuer et de modifier ce code, à condition
# de conserver cette notice et de mentionner que je suis l’auteur
# de tout ou partie du code si vous le réutilisez.
# -----------------------------------------------------------------------------
# Author       : TRISTAN NAULEAU
# Date         : 2025-07-12
# License      : GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
#
# This work is freely distributed under the terms of the
# GNU GPL v3 (https://www.gnu.org/licenses/gpl-3.0.html).
# You are free to redistribute and modify this code, provided that
# you keep this notice and mention that I am the author
# of all or part of the code if you reuse it.
# -----------------------------------------------------------------------------
"""

╔═════════════════════════════════════════════════════════════════════════════════╗
║ ZeAnalyser / ZeSeestarStacker Project                                           ║
║                                                                                 ║
║ Auteur  : Tinystork, seigneur des couteaux à beurre (aka Tristan Nauleau)       ║
║ Partenaire : J.A.R.V.I.S. (/ˈdʒɑːrvɪs/) — Just a Rather Very Intelligent System ║ 
║              (aka ChatGPT, Grand Maître du ciselage de code)                    ║
║                                                                                 ║
║ Licence : GNU General Public License v3.0 (GPL-3.0)                             ║
║                                                                                 ║
║ Description :                                                                   ║
║   Ce programme a été forgé à la lueur des pixels et de la caféine,              ║
║   dans le but noble de transformer des nuages de photons en art                 ║
║   astronomique. Si vous l’utilisez, pensez à dire “merci”,                      ║
║   à lever les yeux vers le ciel, ou à citer Tinystork et J.A.R.V.I.S.           ║
║   (le karma des développeurs en dépend).                                        ║
║                                                                                 ║
║ Avertissement :                                                                 ║
║   Aucune IA ni aucun couteau à beurre n’a été blessé durant le                  ║
║   développement de ce code.                                                     ║
╚═════════════════════════════════════════════════════════════════════════════════╝


╔═════════════════════════════════════════════════════════════════════════════════╗
║ ZeAnalyser / ZeSeestarStacker Project                                           ║
║                                                                                 ║
║ Author  : Tinystork, Lord of the Butter Knives (aka Tristan Nauleau)            ║
║ Partner : J.A.R.V.I.S. (/ˈdʒɑːrvɪs/) — Just a Rather Very Intelligent System    ║ 
║           (aka ChatGPT, Grand Master of Code Chiseling)                         ║
║                                                                                 ║
║ License : GNU General Public License v3.0 (GPL-3.0)                             ║
║                                                                                 ║
║ Description:                                                                    ║
║   This program was forged under the sacred light of pixels and                  ║
║   caffeine, with the noble intent of turning clouds of photons into             ║
║   astronomical art. If you use it, please consider saying “thanks,”             ║
║   gazing at the stars, or crediting Tinystork and J.A.R.V.I.S. —                ║
║   developer karma depends on it.                                                ║
║                                                                                 ║
║ Disclaimer:                                                                     ║
║   No AIs or butter knives were harmed in the making of this code.               ║
╚═════════════════════════════════════════════════════════════════════════════════╝
"""

# Fichier pour l'internationalisation (i18n) et les infobulles

translations = {
    'fr': {
            
        # --- Fenêtre principale ---
        'window_title': "ZeAnalyser {version} — Analyseur d'Images Astronomiques",
        'status_ready': "Prêt",
        'status_analysis_start': "Démarrage de l'analyse...",
        'status_analysis_prep': "Préparation de l'analyse...",
        'status_discovery_start': "Recherche des fichiers FITS...",
        'status_satdet_wait': "Détection traînées (acstools)... Patientez...",
        'status_satdet_no_file': "Détection traînées: Aucun fichier FITS trouvé.",
        'status_satdet_done': "Détection de traînées terminée.",
        'status_satdet_error': "Erreur lors de la détection de traînées.",
        'status_satdet_dep_error': "Erreur dépendance détection (scipy/skimage?).",
        'status_snr_start': "Analyse: {file} ({i}/{total})",
        'status_analysis_done': "Analyse terminée.",
        'status_analysis_done_some': "Analyse terminée. {processed} traités, {moved} actions (déplacé/supprimé), {errors} erreurs fichier.",
        'status_analysis_done_ok': "Analyse terminée avec succès.",
        'status_analysis_done_no_valid': "Analyse terminée. Aucune image traitable trouvée ou tous les dossiers ont été ignorés.", # Modifié
        'status_analysis_done_errors': "Analyse terminée avec des erreurs critiques.",
        'status_analysis_cancelling': "Annulation en cours…",
        'status_analysis_cancelled': "Analyse annulée.",
        'logic_cancellation_requested': "Annulation demandée…",
        'logic_analysis_cancelled': "Analyse annulée.",
        'logic_reanalysis_marker_invalidated': "Ancien marqueur de complétion invalidé avant ré-analyse ({count}).",
        'logic_marker_invalidation_error': "Impossible d'invalider le marqueur avant ré-analyse dans {dir} : {e}",
        'status_log_error': "Erreur écriture log",
        'status_dir_create_error': "Erreur création dossier: {e}",
        'status_custom': "{text}",

        # --- Onglets principaux ---
        'project_tab_title': "Projet",
        'organizer_tab_title': "Organizer",
        'results_tab_title': "Résultats",
        'stack_tab_title': "Plan de stack",
        'preview_tab_title': "Aperçu",
        'settings_tab_title': "Paramètres / Préférences",

        # --- Cadres ---
        'config_frame_title': "Configuration Générale",
        'snr_frame_title': "Analyse SNR & Sélection",
        'trail_frame_title': "Détection Traînées",
        'action_frame_title': "Action sur Images Rejetées",
        'display_options_frame_title': "Options d'Affichage",
        'results_frame_title': "Résultats / Journal",
        'help_menu_label': "Aide",
        'about_action_label': "À propos",
        'no_preview_selected': "Aucun aperçu sélectionné.",
        'preview_hist_label_na': "Histogramme : N/D",
        'preview_apply_stretch': "Appliquer l'étirement",
        'preview_stretch_min': "Étirement min",
        'preview_stretch_max': "max",
        'preview_loading': "Chargement...",
        'preview_failed': "Impossible de charger l'aperçu.",
        'preview_file_missing': "Fichier introuvable.",
        'preview_stats_fmt': "Min:{min}  Max:{max}  Avg:{mean}  Std:{std}",
        'preview_tb_prev': "Image précédente",
        'preview_tb_next': "Image suivante",
        'preview_tb_delete': "Supprimer l'image",
        'preview_open': "Ouvrir un fichier",
        'preview_fit': "Adapter",
        'preview_1_1': "1:1",
        'preview_zoom_in': "Zoom +",
        'preview_zoom_out': "Zoom -",
        'preview_reset': "Réinitialiser",
        'preview_clear': "Effacer",
        'preview_hist_zoom': "Zoom hist",
        'preview_hist_zoom_tip': "Zoomer l'histogramme sur l'étirement courant",
        'preview_hist_zoom_reset': "Histo 1:1",
        'preview_hist_zoom_reset_tip': "Revenir à la vue complète",
        'preview_delete_title': "Supprimer le fichier",
        'preview_delete_text': "Supprimer ce fichier ?\n{filename}",
        'preview_delete_checkbox': "Ne plus afficher ce message (cette session)",
        'preview_delete_failed': "Suppression impossible.",
        'preview_delete_refused': "Suppression refusée (chemin non autorisé).",
        'preview_delete_yes': "Oui",
        'preview_delete_no': "Non",
        'preview_loading': "Chargement...",
        'preview_failed': "Impossible de charger l'apercu.",
        'preview_file_missing': "Fichier introuvable.",
        'preview_stats_fmt': "Min:{min}  Max:{max}  Avg:{mean}  Std:{std}",
        'preview_tb_prev': "Image precedente",
        'preview_tb_next': "Image suivante",
        'preview_tb_delete': "Supprimer l'image",
        'preview_delete_title': "Supprimer le fichier",
        'preview_delete_text': "Supprimer ce fichier?\\n{filename}",
        'preview_delete_checkbox': "Ne plus afficher ce message (cette session)",
        'preview_delete_failed': "Suppression impossible.",
        'preview_delete_refused': "Suppression refusee (chemin non autorise).",
        'preview_delete_yes': "Oui",
        'preview_delete_no': "Non",

        # --- Labels & Champs ---
        'input_dir_label': "Dossier d'entrée:",
        'output_log_label': "Fichier log:",
        'include_subfolders_label': "Inclure les sous-dossiers",
        'include_subfolders_tooltip': "Analyse le dossier sélectionné ainsi que ses sous-dossiers.",
        'organizer_source_label': "Dossier source (lecture seule):",
        'organizer_dest_label': "Dossier destination:",
        'organizer_include_subfolders': "Inclure les sous-dossiers",
        'organizer_dry_run': "Dry run (aucun changement)",
        'organizer_mode_move': "Déplacer les fichiers",
        'organizer_mode_copy': "Copier les fichiers",
        'organizer_skip_organized': "Ignorer _organized existant",
        'bortle_file_label': "Base Bortle (GeoTIFF/KMZ):",
        'browse_bortle_button': "Parcourir",
        'use_bortle_check_label': "Utiliser le classement Bortle",
        'bortle_class_unknown': "Inconnu",
        'lang_label': "Langue:",
        'status_label': "Statut :",
        'elapsed_time_label': "Temps écoulé :",
        'remaining_time_label': "Temps restant :",
        'analyze_snr_check_label': "Activer l'analyse SNR",
        'snr_select_mode_label': "Mode de Sélection SNR:",
        'snr_mode_percent': "Top Pourcentage (%)",
        'snr_mode_threshold': "Seuil SNR (>)",
        'snr_mode_none': "Tout Garder",
        'snr_reject_dir_label': "Dossier Rejet (Faible SNR):",
        'detect_trails_check_label': "Activer détection traînées",
        'sigma_label': "Sigma:", 'low_thresh_label': "Low Thr:", 'h_thresh_label': "High Thr:",
        'line_len_label': "Line Len:", 'small_edge_label': "Small Edge:", 'line_gap_label': "Line Gap:",
        'trail_reject_dir_label': "Dossier Rejet (Traînées):",
        'action_label': "Action:", 'action_mode_move': "Déplacer vers dossier Rejet", 'action_mode_delete': "Supprimer Définitivement", 'action_mode_none': "Ne Rien Faire (Tout Garder)",
        'apply_immediately': "Appliquer immédiatement",
        'sort_snr_check_label': "Trier les résultats par SNR décroissant",
        'filter_results_placeholder': "Filtrer les résultats...",
        'filter_stack_plan_placeholder': "Filtrer le plan de stack...",
        'project_input_placeholder': "Aucun dossier d'entrée sélectionné",
        'project_log_placeholder': "Aucun fichier log sélectionné",
        'bortle_path_placeholder': "Chemin vers la base Bortle...",
        'results_filter_snr_min': "SNR ≥",
        'results_filter_snr_max': "SNR ≤",
        'results_filter_fwhm_max': "FWHM ≤",
        'results_filter_ecc_max': "ECC ≤",
        'results_filter_trails_any': "Tous",
        'results_filter_trails_yes': "Oui",
        'results_filter_trails_no': "Non",

        # --- Boutons ---
        'browse_button': "Parcourir",
        'analyse_button': "Analyser les images",
        'analyse_stack_button': "Analyser et Empiler", # Clé pour le nouveau bouton
        'token_dependency_missing_notice': "Fonctionnalité désactivée : token.zsss introuvable dans le dossier parent du projet.",
        'visualize_button': "Visualiser les résultats",
        'open_log_button': "Ouvrir le fichier log",
        'manage_markers_button': "Gérer Marqueurs", # <-- NOUVEAU
        'quit_button': "Quitter",
        'return_button_text': "Retour",
        'export_button': "Exporter Liste Recommandée (.txt)",
        'Fermer': "Fermer",
        'use_best_reference_button': 'Envoyer Référence',
        'save_reference_button': 'Sauvegarder Référence',
        'Exporter Toutes Conservées': "Exporter Toutes Conservées",
        'apply_snr_rejection_button': "Appliquer Rejet SNR",
        'visual_apply_snr_button': "Appliquer Rejet SNR",
        'apply_starcount_rejection': "Appliquer Rejet Starcount",
        'organize_files_button': "Organiser fichiers",
        'organizer_scan_btn': "Scan / Prévisualisation",
        'organizer_apply_btn': "Appliquer",
        'organizer_cancel_btn': "Annuler",
        'apply_reco_button': "Appliquer Recommandations",
        'visual_apply_reco_button': "Appliquer Recommandations",
        'create_stack_plan_button': "Créer plan de stack",
        'stack_export_csv': "Exporter le plan en CSV",
        'stack_prepare_script': "Préparer le script d'empilage",
        'cancel_button': "Annuler",
        'close_button': "Fermer",
        'stack_plan_window_title': "Plan de stack",
        'include_exposure_in_batch': "Inclure le temps de pose dans le batch",
        'generate_plan_button': "Générer le plan",
        'stack_plan_alert_no_analysis': "Analyse non effectuée.",
        'stack_plan_preview_total': "Images sélectionnées: {count}",
        'stack_plan_preview_batches': "Nombre de batchs: {count}",
        'stack_plan_autoload_loaded': "Plan chargé depuis : {path}",
        'stack_plan_autoload_missing': "Aucun stack_plan.csv dans le dossier projet.",
        'stack_plan_autoload_too_large': "stack_plan.csv trop volumineux, chargement ignoré.",
        'stack_plan_script_saved': "Script d'empilage écrit : {path}",
        'stack_plan_script_failed': "Échec écriture script : {e}",
        'stack_plan_export_saved': "Plan exporté : {path}",
        'stack_plan_export_failed': "Échec export plan : {e}",
        'stack_plan_created': "Plan de stack créé : {path}",
        'mount': "Monture",
        'bortle': "Bortle",
        'telescope': "Télescope",
        'session_date': "Date de session",
        'filter': "Filtre",
        'exposure': "Temps de pose",
        'ascending': "Croissant",
        'descending': "Décroissant",
        'sort_order': "Ordre de tri",

        # --- Textes acstools status ---
        'acstools_ok': "(acstools disponible)", 'acstools_missing': "(acstools non trouvé ou incompatible)", 'acstools_sig_error': "(fonction detsat incompatible)",

        # --- Messages Box ---
        'msg_error': "Erreur", 'msg_warning': "Attention", 'msg_info': "Information",
        'msg_missing_logic': "Le fichier analyse_logic.py est manquant.", 'msg_input_dir_invalid': "Dossier d'entrée invalide.", 'msg_log_file_missing': "Fichier log non spécifié.",
        'non spécifié': "non spécifié", 'confirm_delete': "Êtes-vous sûr de vouloir supprimer définitivement les fichiers rejetés ? Cette action est irréversible.", 'snr_value_missing': "Veuillez entrer une valeur pour la sélection SNR (% ou seuil).", 'snr_value_invalid': "Valeur invalide pour la sélection SNR. Doit être numérique.",
        'msg_satdet_incompatible': "Détection activée mais acstools/satdet n'est pas compatible ou disponible.", 'msg_params_invalid': "Paramètres invalides: {e}", 'msg_analysis_running': "Une analyse est déjà en cours.",
        'Analyse en cours, quitter quand même?': "Une analyse est en cours. Voulez-vous vraiment quitter ?", 'msg_no_results_visualize': "Aucun résultat à visualiser.", 'msg_analysis_wait_visualize': "Attendez la fin de l'analyse pour visualiser.", 'msg_results_incomplete': "Résultats incomplets ou analyse terminée avec erreurs.",
        'Affichage des données disponibles.': "Affichage des données disponibles.",
        'msg_log_not_exist': "Le fichier log n'existe pas ou n'est pas spécifié.", 'msg_log_open_error': "Impossible d'ouvrir '{path}':\n{e}", 'msg_export_no_images': "Aucune image à exporter.", 'msg_export_success': "Liste de {count} fichiers exportée vers:\n{path}", 'msg_export_error': "Erreur écriture fichier:\n{e}",
        'msg_dep_missing_title': "Dépendances Manquantes", 'msg_dep_missing_text': "Bibliothèques manquantes:\n- {deps}\n\nInstaller via pip ?", 'msg_dep_installing': "Installation dépendances...", 'msg_dep_install_pkg': "Installation de {package}...", 'msg_dep_install_success': " -> Succès.", 'msg_dep_install_fail': " -> ÉCHEC: {e}", 'msg_dep_install_error': "Impossible d'installer {package}.\n{e}", 'msg_dep_install_done': "Dépendances installées. Redémarrez l'application.", 'msg_dep_install_partial': "Certaines dépendances n'ont pu être installées.", 'msg_dep_error_continue': "Dépendances manquantes. L'application pourrait mal fonctionner.",
        'msg_tkinter_error': "Erreur Tkinter:\n{e}", 'msg_unexpected_error': "Erreur inattendue:\n{e}",
        'msg_organize_done': "{count} fichiers organisés.",
        'msg_organize_failed': "Organisation échouée: {e}",
        'organizer_summary_title': "Résumé Organizer",
        'organizer_scan_start': "Scan Organizer en cours...",
        'organizer_scan_done': "Scan Organizer terminé.",
        'organizer_apply_start': "Application du plan Organizer...",
        'organizer_apply_done': "Application Organizer terminée.",
        'organizer_error': "Erreur Organizer",
        'organizer_warn_paths_invalid': "Choisissez des dossiers source et destination valides.",
        'organizer_paths_moved_warning': "Les fichiers ont été déplacés/copés. Si des résultats d'analyse étaient affichés, ils peuvent référencer d'anciens chemins. Relancez une analyse en pointant sur le dossier _organized.",
        'msg_stack_plan_write_error': "Impossible d'écrire '{path}'. Fichier utilisé ou dossier non accessible.",
        'command_file_missing': "Fichier de commande introuvable pour le stacker.",
        'command_file_write_error': "Erreur d'écriture du fichier de commande : {e}",
        'stack_command_written': "Fichier de commande écrit : {path}",

        # --- Fenêtre Visualisation ---
        'visu_window_title': "Visualisation des résultats",
        'results_visualisation_title': "Résultats visuels",
        'results_summary_title': "Résumé des résultats",
        'visu_tab_snr_dist': "Distribution SNR", 'visu_tab_snr_comp': "Comparaison SNR", 'visu_tab_sat_trails': "Traînées Détectées", 'visu_tab_raw_data': "Données Détaillées", 'visu_tab_recom': "Recommandations Stacking",
        'visu_snr_dist_title': 'Distribution du Rapport Signal/Bruit (SNR)', 'visu_snr_dist_xlabel': 'SNR', 'visu_snr_dist_ylabel': 'Nombre d\'images', 'visu_snr_dist_no_data': "Aucune donnée SNR valide",
        'snr_statistics_title': "Statistiques SNR",
        'fwhm_statistics_title': "Statistiques FWHM",
        'bortle_distribution_title': "Distribution Bortle",
        'starcount_distribution_tab': "Distribution Starcount",
        'starcount_distribution_title': "Distribution Starcount",
        'starcount_label': "Nombre d'étoiles",
        'number_of_images': "Nombre d'images",
        'visu_tab_fwhm_dist': "Distribution FWHM",
        'visu_tab_ecc_dist': "Distribution Excentricité",
        'fwhm_distribution_title': "Distribution du FWHM",
        'ecc_distribution_title': "Distribution de l'excentricité",
        'visu_tab_fwhm_vs_e': "FWHM vs e",
        'visu_scatter_fwhm_label': "FWHM",
        'visu_scatter_ecc_label': "e",
        'visu_fwhm_no_data': "Aucune donnée FWHM valide",
        'visu_ecc_no_data': "Aucune donnée e valide",
        'filter_fwhm': "Filtre FWHM",
        'filter_ecc': "Filtre Excentricité",
        'visu_snr_comp_best_title': 'Top {n} Images (Meilleur SNR)', 'visu_snr_comp_worst_title': 'Bottom {n} Images (Pire SNR)', 'visu_snr_comp_xlabel': 'SNR', 'visu_snr_comp_no_data': "Pas assez d'images avec SNR valide pour comparer.",
        'visu_sat_pie_title': 'Proportion d\'images avec/sans traînées détectées', 'visu_sat_pie_with': 'Avec Traînées', 'visu_sat_pie_without': 'Sans Traînées', 'visu_sat_pie_no_data': "Aucune image analysée pour les traînées.",
        'visu_data_col_file': "Fichier (Relatif)", 'visu_data_col_snr': "SNR", 'visu_data_col_bg': "Fond", 'visu_data_col_noise': "Bruit", 'visu_data_col_pixsig': "PixSig", 'visu_data_col_trails': "Traînées?", 'visu_data_col_nbseg': "Nb Seg.",
        'Statut': "Statut", 'Action': "Action", 'Raison Rejet': "Raison Rejet", 'Commentaire': "Commentaire",
        'visu_recom_frame_title': "Recommandation (Images Conservées)",
        'reco_starcount_min_pct': "Starcount min (percentile)",
        'reco_snr_min_pct': "SNR min (percentile)",
        'reco_fwhm_max_pct': "FWHM max (percentile)",
        'reco_ecc_max_pct': "Excentricité max (percentile)",
        'use_starcount_chk': "Utiliser Starcount",
        'tooltip_use_starcount': (
            "Active un filtre supplémentaire basé sur le nombre d'étoiles détectées. "
            "Utile pour éliminer les poses voilées / nuageuses, ou avec mauvaise transparence. "
            "À désactiver pour des objets très diffus (nébuleuses) où le starcount varie peu."
        ),
        'visu_recom_text': "Suggestion: Utiliser les {count} images conservées avec SNR >= {p75:.2f} (P25)",
        'visu_recom_text_both': "Suggestion: Utiliser les {count} images conservées avec SNR ≥ {snr_p25:.2f} (P25) et Starcount ≥ {sc_p25:.0f} (P25)",
        'visu_recom_text_all': "Suggestion : utiliser {count} images avec SNR ≥ P25, FWHM ≤ P75 et e ≤ P75",
        'visu_recom_col_file': "Fichier (Relatif)",
        'visu_recom_col_snr': "SNR",
        'visu_recom_col_fwhm': "FWHM",
        'visu_recom_col_ecc': "Excentricité",
        'visu_recom_col_starcount': "Starcount",
        'visu_recom_no_selection': "Aucune image conservée ne dépasse le seuil de recommandation.",
        'visu_recom_not_enough': "Moins de 5 images conservées valides. Utilisez/Exportez toutes les images conservées.",
        'visu_recom_no_data': "Aucune donnée SNR valide pour recommandation.",
        'Toutes les images conservées valides': "Toutes les images conservées valides",
        'visu_recom_resume_snr': "SNR ≥ {value:.2f}",
        'visu_recom_resume_fwhm': "FWHM ≤ {value:.2f}",
        'visu_recom_resume_ecc': "e ≤ {value:.3f}",
        'visu_recom_resume_starcount': "Starcount ≥ {value:.0f}",

        # --- Infobulles (Tooltips) ---
        'tooltip_sigma': "Sigma du filtre Gaussien avant détection contours (flou). Défaut: 2.0", 'tooltip_low_thresh': "Seuil bas Canny (0-1). Détecte bords potentiels. Bas=Sensible bruit. Défaut acstools: 0.1", 'tooltip_h_thresh': "Seuil haut Canny (0-1). Ancre bords forts. >= Low Thr. Bas=Permissif. Défaut acstools: 0.5", 'tooltip_line_len': "Longueur min. (px) segment final pour être une traînée. Défaut acstools: 150", 'tooltip_small_edge': "Longueur min. (px) contour initial (par Canny). Filtre bruit avant Hough. Défaut acstools: 60", 'tooltip_line_gap': "Écart max (px) pour joindre segments. Défaut acstools: 75", 'tooltip_snr_value': "Entrez % (ex: 80) ou seuil SNR (ex: 5.5). Ignoré si Tout Garder.",
        'tooltip_apply_snr_rejection': "Appliquer les rejets SNR différés",
        'tooltip_apply_starcount_rejection': "Appliquer les actions Starcount différées",
        'tooltip_analyze_snr': "Active l'analyse SNR pour chaque image et permet la sélection automatique.",
        'tooltip_snr_mode_percent': "Sélectionne les meilleures images selon un pourcentage de SNR.",
        'tooltip_snr_mode_threshold': "Garde les images dont le SNR dépasse ce seuil.",
        'tooltip_detect_trails': "Active la détection de traînées satellites avec les paramètres indiqués.",
        'tooltip_reject_move': "Déplacer automatiquement les images rejetées vers les dossiers configurés.",
        'tooltip_reject_delete': "Supprimer définitivement les images rejetées après analyse.",
        'tooltip_apply_recommendations': "Appliquer les recommandations de conservation aux fichiers analysés.",
        'tooltip_manage_markers': "Ouvrir le dossier pour gérer les fichiers marqueurs générés par l'analyse.",
        'tooltip_create_stack_plan': "Générer un plan d'empilage CSV basé sur les images conservées.",

        # --- Textes Logique ---
        # Prefixes utilisés par la logique d'analyse pour formater les messages
        # affichés dans la fenêtre de résultats. Ajout de "{text}" pour permettre
        # l'insertion du contenu fourni par le code appelant.
        'logic_info_prefix': "INFO: {text}",
        'logic_log_prefix': "LOG: {text}",
        'logic_status_prefix': "STATUS: {text}",
        'logic_warn_prefix': "Avertissement: {text}",
        'logic_error_prefix': "Erreur: {text}",
        'logic_sat_incomp': "Détection satellites non disponible ou incompatible.", 'logic_sigma_invalid': "Sigma invalide ({e}), utilisation de {default}", 'logic_lowthr_invalid': "Low Thresh invalide ({e}), utilisation de {default}", 'logic_highthr_invalid': "High Thresh invalide ({e}), utilisation de {default}",
        'logic_satdet_params': "Détection avec: sigma={sigma}, low={low_thresh}, high={h_thresh}, chips={chips}, line_len={line_len}, small_edge={small_edge}, line_gap={line_gap}",
        'logic_satdet_errors_title': "Erreurs spécifiques reportées par satdet:", 'logic_satdet_errors_item': "  - {fname} (ext {ext}): {msg}", 'logic_satdet_errors_none': "  (Aucune erreur pertinente à afficher)",
        'logic_satdet_import_error': "Erreur importation pour satdet: {e}. Vérifiez scipy/skimage.", 'logic_satdet_major_error': "Erreur majeure lors de l'appel à acstools.satdet.detsat: {e}",
        'logic_dir_created': "Dossier créé: {path}", 'logic_dir_create_error': "Erreur création dossier {path}: {e}", 'logic_log_init_error': "Impossible d'écrire dans le fichier log initial {path}: {e}",
        'logic_no_fits_satdet': "Aucun fichier FITS trouvé dans {path} pour détection.", 'logic_no_fits_snr': "Aucun fichier FITS (.fit, .fits) trouvé pour l'analyse SNR.",
        'logic_snr_start': "Démarrage de l'analyse individuelle...", 'logic_fits_no_data': "{file} - Pas de données image dans HDU 0.", 'logic_snr_info': "  {file}: SNR={snr:.2f}, Fond={bg:.2f}", 'logic_trail_info': "    Traînées (segments): {status} ({count})", 'logic_trail_yes': "Oui", 'logic_trail_no': "Non",
        'logic_moved_info': "-> Déplacé vers {folder}", 'logic_move_skipped': "    Info: {file} n'existait plus à l'emplacement source pour action.", 'logic_move_error': "    Erreur déplacement {file}: {e}", 'logic_file_error': "Erreur analyse fichier {file}: {e}",
        'logic_source_outside_project': "Action ignorée : le fichier source se trouve hors du dossier du projet. Source : {source} — Projet : {root}",
        'logic_log_summary_error': "Erreur lors de l'écriture du résumé du log ({path}): {e}", 'logic_final_snr': "SNR moyen global: {mean:.2f}", 'logic_final_trails': "Images avec traînées détectées: {count} ({percent:.1f}%)", 'logic_final_no_success': "Aucune image n'a pu être traitée avec succès.",
        # i18n P0.5: dedicated keys for migrated analyse_logic user-facing messages (FR)
        'logic_snr_pending_none': 'Aucune action SNR en attente à appliquer.',
        'logic_snr_apply_start': 'Application des actions SNR différées sur {total} fichiers...',
        'logic_snr_apply_item': 'Action SNR sur {rel} ({i}/{total})',
        'logic_snr_deferred_deleted': 'Fichier supprimé (SNR différé): {rel}',
        'logic_snr_deferred_delete_error': 'Erreur suppression SNR différé {rel}: {e}',
        'logic_snr_apply_done': '{count} actions SNR différées appliquées.',
        'logic_trail_pending_none': 'Aucune action Traînées en attente.',
        'logic_trail_apply_start': 'Application des actions Traînées différées sur {total} fichiers...',
        'logic_trail_apply_item': 'Action Traînées sur {rel} ({i}/{total})',
        'logic_trail_deferred_deleted': 'Fichier supprimé (Traînées différé): {rel}',
        'logic_trail_deferred_delete_error': 'Erreur suppression Traînées différé {rel}: {e}',
        'logic_trail_apply_done': '{count} actions Traînées différées appliquées.',
        'logic_reco_pending_none': 'Aucune action recommandation en attente.',
        'logic_reco_apply_start': 'Application des actions recommandation sur {total} fichiers...',
        'logic_reco_apply_item': 'Action reco sur {rel} ({i}/{total})',
        'logic_reco_deferred_deleted': 'Fichier supprimé (reco): {rel}',
        'logic_reco_deferred_delete_error': 'Erreur suppression reco {rel}: {e}',
        'logic_reco_apply_done': '{count} actions recommandation appliquées.',
        'logic_org_none': 'Aucun fichier à organiser.',
        'logic_org_start': 'Organisation de {total} fichiers...',
        'logic_org_done': '{count} fichiers organisés.',
        'logic_bortle_load_error': 'Erreur de chargement du raster Bortle : {e}',
        'logic_input_dir_invalid': "Dossier d'entrée invalide: {dir}",
        'logic_log_file_unspecified': 'Fichier log non spécifié.',
        'logic_snr_reject_dir_missing': 'Chemin dossier rejet SNR non spécifié mais déplacement activé.',
        'logic_snr_reject_not_dir': "Chemin rejet SNR n'est pas un dossier: {path}",
        'logic_trail_reject_dir_missing': 'Chemin dossier rejet Trail non spécifié mais déplacement activé.',
        'logic_trail_reject_not_dir': "Chemin rejet Trail n'est pas un dossier: {path}",
        'logic_subdir_excluded': 'Exclusion du sous-dossier de rejet: {path}',
        'logic_marker_dir_skipped': 'Ignoré (marqueur trouvé): {path}',
        'logic_walk_dir_error': 'Erreur lors du parcours du dossier {dir}: {e}',
        'logic_marker_created_no_fits': 'Marqueur créé (aucun FITS): {path}',
        'logic_marker_create_error_no_fits': 'Impossible de créer le fichier marqueur (aucun FITS) dans {dir}: {e}',
        'logic_fits_found': '{count} fichiers FITS trouvés pour analyse (hors dossiers ignorés).',
        'logic_snr_pool_fallback': 'Echec pool SNR ({e}), fallback séquentiel',
        'logic_snr_loop_errors': "{count} erreur(s) rencontrée(s) pendant l'analyse SNR initiale.",
        'logic_fwhm_ecc_measurement_failures': "Échec(s) de mesure FWHM/ECC : {count}. Premier exemple : {file} ({reason})",
        'logic_snr_threshold_invalid': "Seuil SNR invalide : '{value}'",
        'logic_snr_percent_invalid': "Valeur pourcentage invalide: '{value}' ({e}).",
        'logic_snr_apply_marking': 'Application du marquage/rejet SNR et actions...',
        'logic_snr_threshold_applied': 'Seuil SNR appliqué: {value}',
        'logic_snr_reject_immediate': 'SNR Rejet (immédiat): {rel} (SNR: {snr} < {threshold})',
        'logic_snr_mark_deferred': 'SNR Marqué pour rejet (différé): {rel} (SNR: {snr} < {threshold})',
        'logic_snr_file_deleted': 'Fichier supprimé (SNR): {rel}',
        'logic_snr_delete_error': 'Erreur suppression SNR {rel}: {e}',
        'logic_trail_module_missing': "Erreur: trail_module n'est pas chargé ou manque run_trail_detection.",
        'logic_trail_no_eligible': 'Aucun fichier éligible pour la détection de traînées après filtre SNR.',
        'logic_trail_detection_start': 'Lancement détection traînées...',
        'logic_trail_pool_error': 'Erreur pool trail: {e}',
        'logic_trail_apply_marking': 'Application du rejet Traînées et actions...',
        'logic_trail_reject': 'Trail Rejet: {rel} ({count} segments)',
        'logic_trail_file_deleted': 'Fichier supprimé (Trail): {rel}',
        'logic_trail_delete_error': 'Erreur suppression Trail {rel}: {e}',
        'logic_marker_creation_start': 'Création des fichiers marqueurs...',
        'logic_marker_created': 'Marqueur créé: {path}',
        'logic_marker_create_error': 'Impossible de créer le fichier marqueur dans {dir}: {e}',
        'logic_marker_skipped_persistence_failure': "Marqueur non créé : l'état persistant final n'a pas pu être enregistré dans {path}.",
        'logic_log_finalize_error': 'Impossible de finaliser le fichier log {path}: {e}',
        'logic_csv_pollution_written': 'CSV pollution écrit: {name}',
        'logic_csv_pollution_error': 'Erreur écriture CSV pollution: {e}',
        # Messages relatifs au plan d'empilement (stack plan)
        'stack_plan_summary': "Plan d'empilement créé : {selected} image(s) sélectionnée(s) sur {total} images analysées ({pct:.1f} %) -> {filename}",
        'stack_plan_summary_no_total': "Plan d'empilement créé : {selected} entrée(s) dans {filename}",
        'stack_plan_reminder': "Rappel : le plan d'empilement ne contient que les images retenues après filtrage (SNR / traînées / critères d'analyse).",
        'Liste dimages recommandées': "Liste d'images recommandées", 'Critère': "Critère", 'Généré le': "Généré le", 'Nombre dimages': "Nombre d'images",
        'Fichiers log': "Fichiers log", 'Tous les fichiers': "Tous les fichiers", 'Fichiers Texte': "Fichiers Texte",

        # --- Textes pour la gestion des marqueurs ---
        'marker_window_title': "Gérer les Marqueurs d'Analyse",
        'marker_info_label': "Dossiers marqués comme analysés :",
        'marker_none_found': "Aucun dossier marqué trouvé.",
        'marker_project_root_label': "Racine du projet",
        'marker_select_none': "Veuillez sélectionner un ou plusieurs dossiers dans la liste.",
        'marker_confirm_delete_selected': "Supprimer les marqueurs pour les {count} dossiers sélectionnés ?\nCela forcera leur ré-analyse au prochain lancement.",
        'marker_confirm_delete_all': "Supprimer TOUS les marqueurs ({count}) dans le dossier '{folder}' et ses sous-dossiers analysables ?\nCela forcera une ré-analyse complète.",
        'marker_delete_selected_button': "Supprimer Sélection",
        'marker_delete_all_button': "Supprimer Tout",
        'marker_delete_errors': "Erreurs lors de la suppression de certains marqueurs:\n",
        'marker_delete_selected_success': "{count} marqueur(s) supprimé(s).",
        'marker_delete_all_success': "Tous les {count} marqueur(s) trouvés ont été supprimés.",
        'marker_scan_error': "Erreur lors du parcours des dossiers :\n{e}",
        'marker_rescan_error': "Erreur lors du nouveau parcours des dossiers",
        'gui_project_restored': "Projet existant restauré : {path} ({count} résultat(s)).",
        'gui_project_log_no_reusable_results': "Le fichier log existe mais ne contient aucun résultat réutilisable : {path}",
        'gui_project_marker_invalid': "Les métadonnées du marqueur de projet sont invalides : {path}",
        'gui_project_restore_failed': "Impossible de restaurer l'état du projet {path} : {e}",
        
        #--- texte actions SNR
        'Aucune action SNR en attente à appliquer.': "Aucune action SNR en attente à appliquer.",
        "L'action sur rejet est 'Ne Rien Faire'. Aucune action ne sera appliquée.": "L'action sur rejet est 'Ne Rien Faire'. Aucune action ne sera appliquée.",
        " pour le déplacement des rejets SNR.": " pour le déplacement des rejets SNR.",
        "\nCeci s'appliquera aux fichiers marqués pour faible SNR.": "\nCeci s'appliquera aux fichiers marqués pour faible SNR.",
        "Application des rejets SNR...": "Application des rejets SNR...",
        "Début application rejets SNR...": "Début application rejets SNR...",
        "Erreur application actions SNR.": "Erreur application actions SNR.",
        "{count} actions SNR appliquées.": "{count} actions SNR appliquées.",
        "Fin application rejets SNR. {count} actions effectuées.": "Fin application rejets SNR. {count} actions effectuées.",
        "Le fichier log a été mis à jour avec les actions SNR.": "Le fichier log a été mis à jour avec les actions SNR.",
        "Échec de l'application des actions SNR.": "Échec de l'application des actions SNR.",
        "Échec application rejets SNR.": "Échec application rejets SNR.",
        # --- GUI log messages (analyse_gui_qt) ---  # i18n P0.6
        'gui_no_recommended_images_to_apply': "Aucune image recommandée à appliquer",
        'gui_stack_plan_autoload_failed': "Échec du chargement automatique du plan de stack : {e}",
        'gui_missing_output_path': "Chemin de sortie manquant — impossible de démarrer l'analyse",
        'gui_using_input_dir_and_log': "Dossier d'entrée utilisé : {input}, fichier log : {log}",
        'gui_trail_reject_dir_required': "ERREUR : le dossier de rejet des traînées est requis pour déplacer les images rejetées (traînées)",
        'gui_snr_reject_dir_required': "ERREUR : le dossier de rejet SNR est requis pour déplacer les images rejetées (SNR)",
        'gui_no_results_stack_plan': "Aucun résultat disponible pour le plan de stack",
        'gui_no_images_kept_for_stacking': "Aucune image conservée pour l'empilage",
        'gui_stack_plan_created_with_batches': "Plan de stack créé : {path} avec {count} batchs",
        'gui_stack_plan_no_results': "La génération du plan de stack n'a retourné aucun résultat",
        'gui_stack_plan_create_error': "Erreur lors de la création du plan de stack : {e}",
        'gui_stacking_script_prepared_preview': "Script d'empilage préparé (mode aperçu)",
        'gui_no_stacking_script_generated': "Aucun script d'empilage généré",
        'gui_stacking_script_prepare_error': "Erreur lors de la préparation du script d'empilage : {e}",
        'gui_no_log_file_selected': "Aucun fichier log sélectionné à ouvrir",
        'gui_log_file_not_found': "Le fichier log n'existe pas",
        'gui_open_log_failed': "Échec de l'ouverture du fichier log : {e}",
        'gui_stack_plan_window_open_error': "Erreur lors de l'ouverture de la fenêtre du plan de stack : {e}",
        'gui_stack_plan_export_failed': "Échec de l'export du plan de stack : {e}",
        'gui_stacking_script_write_failed': "Échec de l'écriture du script d'empilage : {e}",
        'gui_stacking_script_prepare_failed': "Échec de la préparation du script d'empilage : {e}",
        'gui_apply_snr_filter_not_implemented': "Appliquer le filtre SNR depuis la visualisation (pas encore implémenté)",
        'gui_apply_fwhm_filter_not_implemented': "Appliquer le filtre FWHM depuis la visualisation (pas encore implémenté)",
        'gui_visualization_json_decode_error': "ERREUR: Échec du décodage JSON depuis {path}: {e}",
        'gui_visualization_data_load_error': "ERREUR: Échec du chargement des données de visualisation depuis {path}: {e}",
        'gui_marker_manage_error': "Erreur lors de la gestion des marqueurs : {e}",
        'gui_no_results_to_visualise': "Aucun résultat à visualiser",
        'gui_results_visualise_error': "Erreur lors de la visualisation des résultats : {e}",
        'gui_apply_reco_no_results': "Aucun résultat disponible pour appliquer les recommandations",
        'gui_apply_reco_no_paths': "Aucun chemin de fichier recommandé disponible",
        'gui_apply_reco_error': "Erreur lors de l'application des recommandations : {e}",
        'gui_apply_reco_inner_error': "Erreur dans l'application des recommandations : {e}",
        'gui_marked_good_images': "{count} bonnes images marquées",
        'gui_unmarked_images': "{count} images démarquées",
        'gui_organizer_no_plan': "Organisateur : aucun plan à appliquer. Lancez d'abord un scan.",
        'gui_organizer_error': "Erreur de l'organisateur : {text}",
        'gui_auto_organize_error': "Erreur lors de l'organisation automatique : {e}",
        'gui_apply_actions_error': "Erreur lors de l'application des actions {action_type} : {e}",
        'Des actions SNR sont en attente.': "Des actions SNR sont en attente.",


    },
    'en': {
        # --- Main Window ---
        'window_title': "ZeAnalyser {version} — Astronomical Image Analyser",
        'status_ready': "Ready", 'status_analysis_start': "Starting analysis...", 'status_analysis_prep': "Preparing analysis...",
        'status_discovery_start': "Discovering FITS files...", # NEW
        'status_satdet_wait': "Detecting trails (acstools)... Please wait...", 'status_satdet_no_file': "Trail detection: No FITS files found.",
        'status_satdet_done': "Trail detection finished.", 'status_satdet_error': "Error during trail detection.", 'status_satdet_dep_error': "Detection dependency error (scipy/skimage?).",
        'status_snr_start': "Analyzing: {file} ({i}/{total})", 'status_analysis_done': "Analysis finished.",
        'status_analysis_done_some': "Analysis finished. {processed} processed, {moved} actions (moved/deleted), {errors} file errors.",
        'status_analysis_done_ok': "Analysis completed successfully.",
        'status_analysis_done_no_valid': "Analysis finished. No processable images found or all folders were skipped.", # Modified
        'status_analysis_done_errors': "Analysis finished with critical errors.",
        'status_analysis_cancelling': "Cancelling…",
        'status_analysis_cancelled': "Analysis cancelled.",
        'logic_cancellation_requested': "Cancellation requested…",
        'logic_analysis_cancelled': "Analysis cancelled.",
        'logic_reanalysis_marker_invalidated': "Previous completion marker invalidated before reanalysis ({count}).",
        'logic_marker_invalidation_error': "Could not invalidate the marker before reanalysis in {dir}: {e}",
        'status_log_error': "Log writing error", 'status_dir_create_error': "Folder creation error: {e}",
        'status_custom': "{text}",

        # --- Main tabs ---
        'project_tab_title': "Project",
        'organizer_tab_title': "Organizer",
        'results_tab_title': "Results",
        'stack_tab_title': "Stack Plan",
        'preview_tab_title': "Preview",
        'settings_tab_title': "Settings / Preferences",

        # --- Frames ---
        'config_frame_title': "General Configuration", 'snr_frame_title': "SNR Analysis & Selection", 'trail_frame_title': "Trail Detection", 'action_frame_title': "Action on Rejected Images", 'display_options_frame_title': "Display Options", 'results_frame_title': "Results / Log",
        'help_menu_label': "Help", 'about_action_label': "About",

        # --- Labels & Fields ---
        'input_dir_label': "Input Folder:", 'output_log_label': "Log File:",
        'include_subfolders_label': "Include subfolders", # <-- NEW
        'include_subfolders_tooltip': "Analyze the selected folder and its subfolders.",
        'organizer_source_label': "Source folder (read-only):",
        'organizer_dest_label': "Destination folder:",
        'organizer_include_subfolders': "Include subfolders",
        'organizer_dry_run': "Dry run (no changes)",
        'organizer_mode_move': "Move files",
        'organizer_mode_copy': "Copy files",
        'organizer_skip_organized': "Skip already organized",
        'bortle_file_label': "Bortle base (GeoTIFF/KMZ):",
        'browse_bortle_button': "Browse",
        'use_bortle_check_label': "Use Bortle classification",
        'bortle_class_unknown': "Unknown",
        'lang_label': "Language:",
        'status_label': "Status:",
        'elapsed_time_label': "Elapsed:",
        'remaining_time_label': "Remaining:",
        'no_preview_selected': "No preview selected.",
        'preview_hist_label_na': "Histogram: N/A",
        'preview_apply_stretch': "Apply stretch",
        'preview_stretch_min': "Stretch min",
        'preview_stretch_max': "max",
        'preview_loading': "Loading...",
        'preview_failed': "Failed to load preview.",
        'preview_file_missing': "File not found.",
        'preview_stats_fmt': "Min:{min}  Max:{max}  Avg:{mean}  Std:{std}",
        'preview_tb_prev': "Previous image",
        'preview_tb_next': "Next image",
        'preview_tb_delete': "Delete image",
        'preview_open': "Open file",
        'preview_fit': "Fit",
        'preview_1_1': "1:1",
        'preview_zoom_in': "Zoom in",
        'preview_zoom_out': "Zoom out",
        'preview_reset': "Reset",
        'preview_clear': "Clear",
        'preview_hist_zoom': "Hist zoom",
        'preview_hist_zoom_tip': "Zoom histogram to current stretch range",
        'preview_hist_zoom_reset': "Hist 1:1",
        'preview_hist_zoom_reset_tip': "Reset histogram view",
        'preview_delete_title': "Delete file",
        'preview_delete_text': "Delete this file?\n{filename}",
        'preview_delete_checkbox': "Don't show this message again (this session)",
        'preview_delete_failed': "Failed to delete.",
        'preview_delete_refused': "Delete refused (path not allowed).",
        'preview_delete_yes': "Yes",
        'preview_delete_no': "No",
        'preview_loading': "Loading...",
        'preview_failed': "Failed to load preview.",
        'preview_file_missing': "File not found.",
        'preview_stats_fmt': "Min:{min}  Max:{max}  Avg:{mean}  Std:{std}",
        'preview_tb_prev': "Previous image",
        'preview_tb_next': "Next image",
        'preview_tb_delete': "Delete image",
        'preview_delete_title': "Delete file",
        'preview_delete_text': "Delete this file?\\n{filename}",
        'preview_delete_checkbox': "Don't show this message again (this session)",
        'preview_delete_failed': "Failed to delete.",
        'preview_delete_refused': "Delete refused (path not allowed).",
        'preview_delete_yes': "Yes",
        'preview_delete_no': "No",
        'analyze_snr_check_label': "Enable SNR analysis", 'snr_select_mode_label': "SNR Selection Mode:", 'snr_mode_percent': "Top Percent (%)", 'snr_mode_threshold': "SNR Threshold (>)",
        'snr_mode_none': "Keep All", 'snr_reject_dir_label': "Reject Folder (Low SNR):",
        'detect_trails_check_label': "Enable trail detection",
        'sigma_label': "Sigma:", 'low_thresh_label': "Low Thr:", 'h_thresh_label': "High Thr:",
        'line_len_label': "Line Len:", 'small_edge_label': "Small Edge:", 'line_gap_label': "Line Gap:",
        'trail_reject_dir_label': "Reject Folder (Trails):", 'action_label': "Action:", 'action_mode_move': "Move to Reject Folder", 'action_mode_delete': "Delete Permanently", 'action_mode_none': "Do Nothing (Keep All)",
        'apply_immediately': "Apply immediately",
        'sort_snr_check_label': "Sort results by descending SNR",
        'filter_results_placeholder': "Filter results...", 'filter_stack_plan_placeholder': "Filter stack plan...",
        'project_input_placeholder': "No input folder chosen",
        'project_log_placeholder': "No log file chosen",
        'bortle_path_placeholder': "Bortle base path...",
        'results_filter_snr_min': "SNR ≥",
        'results_filter_snr_max': "SNR ≤",
        'results_filter_fwhm_max': "FWHM ≤",
        'results_filter_ecc_max': "ECC ≤",
        'results_filter_trails_any': "Any",
        'results_filter_trails_yes': "Yes",
        'results_filter_trails_no': "No",

        # --- Buttons ---
        'browse_button': "Browse", 'analyse_button':
        "Analyze Images", 'visualize_button': "Visualize Results", 'open_log_button': "Open Log File",
        'analyse_stack_button': "Analyze and Stack", # Key for the new button
        'token_dependency_missing_notice': "Feature disabled: token.zsss is missing from the parent project directory.",
        'manage_markers_button': "Manage Markers", # <-- NEW
        'quit_button': "Quit", 'return_button_text': "Return", 'export_button': "Export Recommended List (.txt)",
        'Fermer': "Close", 'Exporter Toutes Conservées': "Export All Kept",
        'cancel_button': "Cancel", 'close_button': "Close",
        'stack_export_csv': "Export plan as CSV", 'stack_prepare_script': "Prepare stacking script",
        'organizer_scan_btn': "Scan / Preview",
        'organizer_apply_btn': "Apply",
        'organizer_cancel_btn': "Cancel",

        'use_best_reference_button': 'Send Reference',
        'save_reference_button': 'Save Reference',
        # --- acstools status text ---
        'acstools_ok': "(acstools available)", 'acstools_missing': "(acstools not found or incompatible)", 'acstools_sig_error': "(detsat function incompatible)",

        # --- Message Boxes ---
        'msg_error': "Error", 'msg_warning': "Warning", 'msg_info': "Information",
        'msg_missing_logic': "analyse_logic.py file is missing.", 'msg_input_dir_invalid': "Invalid input folder.", 'msg_log_file_missing': "Log file not specified.",
        'non spécifié': "not specified", 'confirm_delete': "Are you sure you want to permanently delete rejected files? This cannot be undone.", 'snr_value_missing': "Please enter a value for SNR selection (% or threshold).", 'snr_value_invalid': "Invalid value for SNR selection. Must be numeric.",
        'msg_satdet_incompatible': "Detection enabled but acstools/detsat is not compatible or available.", 'msg_params_invalid': "Invalid parameters: {e}", 'msg_analysis_running': "An analysis is already in progress.",
        'Analyse en cours, quitter quand même?': "Analysis in progress. Quit anyway?", 'msg_no_results_visualize': "No results to visualize.", 'msg_analysis_wait_visualize': "Wait for the analysis to finish before visualizing.", 'msg_results_incomplete': "Incomplete results or analysis finished with errors.",
        'Affichage des données disponibles.': "Displaying available data.",
        'msg_log_not_exist': "Log file does not exist or is not specified.", 'msg_log_open_error': "Cannot open '{path}':\n{e}", 'msg_export_no_images': "No images to export.", 'msg_export_success': "List of {count} filenames exported to:\n{path}", 'msg_export_error': "Error writing file:\n{e}",
        'msg_dep_missing_title': "Missing Dependencies", 'msg_dep_missing_text': "Missing libraries:\n- {deps}\n\nInstall via pip?", 'msg_dep_installing': "Installing dependencies...", 'msg_dep_install_pkg': "Installing {package}...", 'msg_dep_install_success': " -> Success.", 'msg_dep_install_fail': " -> FAILED: {e}", 'msg_dep_install_error': "Could not install {package}.\n{e}",
        'msg_dep_install_done': "Dependencies installed. Please restart the application.", 'msg_dep_install_partial': "Some dependencies failed to install.", 'msg_dep_error_continue': "Missing dependencies. The application might not work correctly.",
        'msg_tkinter_error': "Tkinter Error:\n{e}", 'msg_unexpected_error': "Unexpected error:\n{e}",
        'msg_organize_done': "{count} files organized.",
        'msg_organize_failed': "Organization failed: {e}",
        'organizer_summary_title': "Organizer summary",
        'organizer_scan_start': "Organizer scan running...",
        'organizer_scan_done': "Organizer scan finished.",
        'organizer_apply_start': "Applying organizer plan...",
        'organizer_apply_done': "Organizer apply finished.",
        'organizer_error': "Organizer error",
        'organizer_warn_paths_invalid': "Please choose valid source and destination folders.",
        'organizer_paths_moved_warning': "Files were moved/copied. If analysis results were displayed, they may point to old paths. Rerun analysis on the _organized folder.",
        'msg_stack_plan_write_error': "Cannot write '{path}'. File is in use or the directory is not writable.",
        'command_file_missing': "Command file for the stacker is missing.",
        'command_file_write_error': "Could not write command file: {e}",
        'stack_command_written': "Command file written: {path}",

        # --- Visualization Window ---
        'visu_window_title': "Results Visualization", 'visu_tab_snr_dist': "SNR Distribution", 'visu_tab_snr_comp': "SNR Comparison", 'visu_tab_sat_trails': "Detected Trails", 'visu_tab_raw_data': "Detailed Data", 'visu_tab_recom': "Stacking Recommendations",
        'results_visualisation_title': "Results visualisation",
        'results_summary_title': "Results summary",
        'visu_snr_dist_title': 'Signal-to-Noise Ratio (SNR) Distribution', 'visu_snr_dist_xlabel': 'SNR', 'visu_snr_dist_ylabel': 'Number of images', 'visu_snr_dist_no_data': "No valid SNR data",
        'snr_statistics_title': "SNR statistics",
        'fwhm_statistics_title': "FWHM statistics",
        'bortle_distribution_title': "Bortle distribution",
        'starcount_distribution_tab': "Starcount Distribution",
        'starcount_distribution_title': "Starcount Distribution",
        'starcount_label': "Starcount",
        'number_of_images': "Number of images",
        'visu_tab_fwhm_dist': "FWHM Distribution",
        'visu_tab_ecc_dist': "Eccentricity Distribution",
        'fwhm_distribution_title': "FWHM Distribution",
        'ecc_distribution_title': "Eccentricity Distribution",
        'visu_tab_fwhm_vs_e': "FWHM vs e",
        'visu_scatter_fwhm_label': "FWHM",
        'visu_scatter_ecc_label': "e",
        'visu_fwhm_no_data': "No valid FWHM data",
        'visu_ecc_no_data': "No valid e data",
        'filter_fwhm': "FWHM Filter",
        'filter_ecc': "Eccentricity Filter",
        'visu_snr_comp_best_title': 'Top {n} Images (Best SNR)', 'visu_snr_comp_worst_title': 'Bottom {n} Images (Worst SNR)', 'visu_snr_comp_xlabel': 'SNR', 'visu_snr_comp_no_data': "Not enough images with valid SNR to compare.",
        'visu_sat_pie_title': 'Proportion of images with/without detected trails', 'visu_sat_pie_with': 'With Trails', 'visu_sat_pie_without': 'Without Trails', 'visu_sat_pie_no_data': "No images analyzed for trails.",
        'visu_data_col_file': "File (Relative)", 'visu_data_col_snr': "SNR", 'visu_data_col_bg': "BG", 'visu_data_col_noise': "Noise", 'visu_data_col_pixsig': "SigPix", 'visu_data_col_trails': "Trails?", 'visu_data_col_nbseg': "Nb Seg.",
        'Statut': "Status", 'Action': "Action", 'Raison Rejet': "Reject Reason", 'Commentaire': "Comment",
        'visu_recom_frame_title': "Recommendation (Kept Images)",
        'reco_starcount_min_pct': "Starcount min (percentile)",
        'use_starcount_chk': "Use Starcount",
        'tooltip_use_starcount': (
            "Adds an extra filter based on the detected star count. "
            "Useful to discard hazy/cloudy subs or poor transparency. "
            "Disable for very diffuse targets (nebulae) where star count is less indicative."
        ),
        'tooltip_analyze_snr': "Enable SNR analysis on each image to drive selection.",
        'tooltip_snr_mode_percent': "Keep the top percentage of images by SNR.",
        'tooltip_snr_mode_threshold': "Keep images whose SNR exceeds this threshold.",
        'tooltip_detect_trails': "Enable satellite trail detection with the configured parameters.",
        'tooltip_reject_move': "Move rejected images automatically into the configured folders.",
        'tooltip_reject_delete': "Permanently delete rejected images after analysis.",
        'tooltip_apply_recommendations': "Apply recommended keep/reject actions to analyzed files.",
        'tooltip_manage_markers': "Open the folder to manage marker files produced by analysis.",
        'tooltip_create_stack_plan': "Generate a CSV stacking plan from kept images.",
        'visu_recom_text': "Suggestion: Use the {count} kept images with SNR >= {p75:.2f} (P25)",
        'visu_recom_text_both': "Suggestion: Use the {count} kept images with SNR \u2265 {snr_p25:.2f} (P25) and Starcount \u2265 {sc_p25:.0f} (P25)",
        'visu_recom_text_all': "Suggestion: use {count} images with SNR \u2265 P25, FWHM \u2264 P75 and e \u2264 P75",
        'visu_recom_col_file': "File (Relative)",
        'visu_recom_col_snr': "SNR",
        'visu_recom_col_fwhm': "FWHM",
        'visu_recom_col_ecc': "Eccentricity",
        'visu_recom_col_starcount': "Starcount",
        'visu_recom_no_selection': "No kept images meet the recommendation threshold.",
        'visu_recom_not_enough': "Fewer than 5 valid kept images. Use/Export all valid kept images.",
        'visu_recom_no_data': "No valid SNR data for recommendation.",
        'Toutes les images conservées valides': "All valid kept images",
        'visu_recom_resume_snr': "SNR ≥ {value:.2f}",
        'visu_recom_resume_fwhm': "FWHM ≤ {value:.2f}",
        'visu_recom_resume_ecc': "e ≤ {value:.3f}",
        'visu_recom_resume_starcount': "Starcount ≥ {value:.0f}",
        'reco_snr_min_pct': "SNR min (percentile)", 'reco_fwhm_max_pct': "FWHM max (percentile)", 'reco_ecc_max_pct': "Eccentricity max (percentile)",

        # --- Tooltips ---
        'tooltip_sigma': "Sigma of Gaussian filter before edge detection (blur). Default: 2.0", 'tooltip_low_thresh': "Lower Canny threshold (0-1). Detects potential edges. Lower=Noisier. acstools default: 0.1", 'tooltip_h_thresh': "Upper Canny threshold (0-1). Anchors strong edges. >= Low Thr. Lower=Permissive. acstools default: 0.5", 'tooltip_line_len': "Min. length (px) of final line segment to be a trail. acstools default: 150", 'tooltip_small_edge': "Min. length (px) of initial edge segment (Canny). Filters noise before Hough. acstools default: 60", 'tooltip_line_gap': "Max allowed gap (px) to link segments. acstools default: 75", 'tooltip_snr_value': "Enter % (e.g., 80) or SNR threshold (e.g., 5.5). Ignored if Keep All.",
        'tooltip_apply_snr_rejection': "Apply pending SNR rejections",
        'tooltip_apply_starcount_rejection': "Apply pending starcount actions",

        # --- Logic Texts ---
        # Prefixes used by the analysis logic to format log lines. Include
        # "{text}" so the caller supplied message is displayed instead of just
        # the prefix.
        'logic_info_prefix': "INFO: {text}",
        'logic_log_prefix': "LOG: {text}",
        'logic_status_prefix': "STATUS: {text}",
        'logic_warn_prefix': "Warning: {text}",
        'logic_error_prefix': "Error: {text}",
        'logic_sat_incomp': "Satellite detection unavailable or incompatible.", 'logic_sigma_invalid': "Invalid Sigma ({e}), using {default}", 'logic_lowthr_invalid': "Invalid Low Thresh ({e}), using {default}", 'logic_highthr_invalid': "Invalid High Thresh ({e}), using {default}",
        'logic_satdet_params': "Detection with: sigma={sigma}, low={low_thresh}, high={h_thresh}, chips={chips}, line_len={line_len}, small_edge={small_edge}, line_gap={line_gap}",
        'logic_satdet_errors_title': "Specific errors reported by satdet:", 'logic_satdet_errors_item': "  - {fname} (ext {ext}): {msg}", 'logic_satdet_errors_none': "  (No relevant errors to display)",
        'logic_satdet_import_error': "Import error for satdet: {e}. Check scipy/skimage.", 'logic_satdet_major_error': "Major error calling acstools.satdet.detsat: {e}",
        'logic_dir_created': "Folder created: {path}", 'logic_dir_create_error': "Error creating folder {path}: {e}", 'logic_log_init_error': "Cannot write to initial log file {path}: {e}",
        'logic_no_fits_satdet': "No FITS files found in {path} for detection.", 'logic_no_fits_snr': "No FITS files (.fit, .fits) found for SNR analysis.",
        'logic_snr_start': "Starting individual file analysis...", 'logic_fits_no_data': "{file} - No image data in HDU 0.", 'logic_snr_info': "  {file}: SNR={snr:.2f}, Background={bg:.2f}", 'logic_trail_info': "    Trails (segments): {status} ({count})", 'logic_trail_yes': "Yes", 'logic_trail_no': "No",
        'logic_moved_info': "-> Moved to {folder}", 'logic_move_skipped': "    Info: {file} no longer existed at source location for action.", 'logic_move_error': "    Error moving {file}: {e}", 'logic_file_error': "Error analyzing file {file}: {e}",
        'logic_source_outside_project': "Action skipped: source file is outside the project directory. Source: {source} — Project: {root}",
        'logic_log_summary_error': "Error writing log summary ({path}): {e}", 'logic_final_snr': "Overall average SNR: {mean:.2f}", 'logic_final_trails': "Images with detected trails: {count} ({percent:.1f}%)", 'logic_final_no_success': "No images could be processed successfully.",
        # i18n P0.5: dedicated keys for migrated analyse_logic user-facing messages (EN)
        'logic_snr_pending_none': 'No pending SNR action to apply.',
        'logic_snr_apply_start': 'Applying deferred SNR actions on {total} files...',
        'logic_snr_apply_item': 'SNR action on {rel} ({i}/{total})',
        'logic_snr_deferred_deleted': 'File deleted (deferred SNR): {rel}',
        'logic_snr_deferred_delete_error': 'Error deleting deferred SNR {rel}: {e}',
        'logic_snr_apply_done': '{count} deferred SNR actions applied.',
        'logic_trail_pending_none': 'No pending trail action.',
        'logic_trail_apply_start': 'Applying deferred trail actions on {total} files...',
        'logic_trail_apply_item': 'Trail action on {rel} ({i}/{total})',
        'logic_trail_deferred_deleted': 'File deleted (deferred trail): {rel}',
        'logic_trail_deferred_delete_error': 'Error deleting deferred trail {rel}: {e}',
        'logic_trail_apply_done': '{count} deferred trail actions applied.',
        'logic_reco_pending_none': 'No pending recommendation action.',
        'logic_reco_apply_start': 'Applying recommendation actions on {total} files...',
        'logic_reco_apply_item': 'Recommendation action on {rel} ({i}/{total})',
        'logic_reco_deferred_deleted': 'File deleted (recommendation): {rel}',
        'logic_reco_deferred_delete_error': 'Error deleting recommendation {rel}: {e}',
        'logic_reco_apply_done': '{count} recommendation actions applied.',
        'logic_org_none': 'No file to organize.',
        'logic_org_start': 'Organizing {total} files...',
        'logic_org_done': '{count} files organized.',
        'logic_bortle_load_error': 'Bortle raster load error: {e}',
        'logic_input_dir_invalid': 'Invalid input folder: {dir}',
        'logic_log_file_unspecified': 'Log file not specified.',
        'logic_snr_reject_dir_missing': 'SNR reject folder path not specified but move enabled.',
        'logic_snr_reject_not_dir': 'SNR reject path is not a folder: {path}',
        'logic_trail_reject_dir_missing': 'Trail reject folder path not specified but move enabled.',
        'logic_trail_reject_not_dir': 'Trail reject path is not a folder: {path}',
        'logic_subdir_excluded': 'Excluding reject subfolder: {path}',
        'logic_marker_dir_skipped': 'Skipped (marker found): {path}',
        'logic_walk_dir_error': 'Error while walking folder {dir}: {e}',
        'logic_marker_created_no_fits': 'Marker created (no FITS): {path}',
        'logic_marker_create_error_no_fits': 'Failed to create marker file (no FITS) in {dir}: {e}',
        'logic_fits_found': '{count} FITS files found for analysis (excluding ignored folders).',
        'logic_snr_pool_fallback': 'SNR pool failure ({e}), falling back to sequential',
        'logic_snr_loop_errors': '{count} error(s) encountered during the initial SNR analysis.',
        'logic_fwhm_ecc_measurement_failures': 'FWHM/ECC measurement failures: {count}. First example: {file} ({reason})',
        'logic_snr_threshold_invalid': "Invalid SNR threshold: '{value}'",
        'logic_snr_percent_invalid': "Invalid percentage value: '{value}' ({e}).",
        'logic_snr_apply_marking': 'Applying SNR marking/rejection and actions...',
        'logic_snr_threshold_applied': 'SNR threshold applied: {value}',
        'logic_snr_reject_immediate': 'SNR rejection (immediate): {rel} (SNR: {snr} < {threshold})',
        'logic_snr_mark_deferred': 'SNR marked for rejection (deferred): {rel} (SNR: {snr} < {threshold})',
        'logic_snr_file_deleted': 'File deleted (SNR): {rel}',
        'logic_snr_delete_error': 'Error deleting SNR {rel}: {e}',
        'logic_trail_module_missing': 'Error: trail_module is not loaded or run_trail_detection is missing.',
        'logic_trail_no_eligible': 'No eligible file for trail detection after SNR filtering.',
        'logic_trail_detection_start': 'Starting trail detection...',
        'logic_trail_pool_error': 'Trail pool error: {e}',
        'logic_trail_apply_marking': 'Applying trail rejection and actions...',
        'logic_trail_reject': 'Trail rejection: {rel} ({count} segments)',
        'logic_trail_file_deleted': 'File deleted (Trail): {rel}',
        'logic_trail_delete_error': 'Error deleting Trail {rel}: {e}',
        'logic_marker_creation_start': 'Creating marker files...',
        'logic_marker_created': 'Marker created: {path}',
        'logic_marker_create_error': 'Failed to create marker file in {dir}: {e}',
        'logic_marker_skipped_persistence_failure': 'Marker not created because final persisted state could not be written to {path}.',
        'logic_log_finalize_error': 'Failed to finalize log file {path}: {e}',
        'logic_csv_pollution_written': 'Pollution CSV written: {name}',
        'logic_csv_pollution_error': 'Pollution CSV write error: {e}',
        # Stacking plan related messages
        'stack_plan_summary': "Stacking plan created: {selected} image(s) selected out of {total} analysed images ({pct:.1f} %) -> {filename}",
        'stack_plan_summary_no_total': "Stacking plan created: {selected} entry/entries in {filename}",
        'stack_plan_reminder': "Reminder: the stacking plan only contains images retained after filtering (SNR / trails / analysis criteria).",
        'Liste dimages recommandées': "Recommended image list", 'Critère': "Criterion", 'Généré le': "Generated on", 'Nombre dimages': "Number of images",
        'Fichiers log': "Log Files", 'Tous les fichiers': "All Files", 'Fichiers Texte': "Text Files",

        # --- Marker Management Texts ---
        'marker_window_title': "Manage Analysis Markers",
        'marker_info_label': "Folders marked as analyzed:",
        'marker_none_found': "No marked folders found.",
        'marker_project_root_label': "Project root",
        'marker_select_none': "Please select one or more folders from the list.",
        'marker_confirm_delete_selected': "Delete markers for the {count} selected folder(s)?\nThis will force re-analysis on the next run.",
        'marker_confirm_delete_all': "Delete ALL markers ({count}) in folder '{folder}' and its analyzable subfolders?\nThis will force a complete re-analysis.",
        'marker_delete_selected_button': "Delete Selected",
        'marker_delete_all_button': "Delete All",
        'marker_delete_errors': "Errors occurred while deleting some markers:\n",
        'marker_delete_selected_success': "{count} marker(s) deleted.",
        'marker_delete_all_success': "All {count} found marker(s) deleted.",
        'marker_scan_error': "Error scanning folders:\n{e}",
        'marker_rescan_error': "Error re-scanning folders",
        'gui_project_restored': "Existing project restored: {path} ({count} result(s)).",
        'gui_project_log_no_reusable_results': "The log file exists but contains no reusable results: {path}",
        'gui_project_marker_invalid': "Project marker metadata is invalid: {path}",
        'gui_project_restore_failed': "Could not restore project state for {path}: {e}",
        'apply_starcount_rejection': "Apply Starcount Rejection",
        'organize_files_button': "Organize Files",
        'apply_reco_button': "Apply Recommendations",
        'visual_apply_reco_button': "Apply Recommendations",
        'create_stack_plan_button': "Create stacking plan",
        'stack_plan_window_title': "Stacking plan",
        'include_exposure_in_batch': "Include exposure in batch",
        'generate_plan_button': "Generate plan",
        'stack_plan_alert_no_analysis': "Analysis not run.",
        'stack_plan_preview_total': "Selected images: {count}",
        'stack_plan_preview_batches': "Batch count: {count}",
        'stack_plan_autoload_loaded': "Plan loaded from: {path}",
        'stack_plan_autoload_missing': "No stack_plan.csv found in project folder.",
        'stack_plan_autoload_too_large': "stack_plan.csv too large, loading skipped.",
        'stack_plan_script_saved': "Stacking script written: {path}",
        'stack_plan_script_failed': "Failed to write script: {e}",
        'stack_plan_export_saved': "Plan exported: {path}",
        'stack_plan_export_failed': "Failed to export plan: {e}",
        'stack_plan_created': "Stacking plan created: {path}",
        'mount': "Mount",
        'bortle': "Bortle",
        'telescope': "Telescope",
        'session_date': "Session date",
        'filter': "Filter",
        'exposure': "Exposure",
        'ascending': "Ascending",
        'descending': "Descending",
        'sort_order': "Sort order",

        #--- Apply SNR
        'apply_snr_rejection_button': "Apply SNR Rejection",
        'visual_apply_snr_button': "Apply SNR Rejection",
        'Des actions SNR sont en attente.': "Pending SNR actions.", # Message de statut
        'Aucune action SNR en attente à appliquer.': "No pending SNR actions to apply.",
        "L'action sur rejet est 'Ne Rien Faire'. Aucune action ne sera appliquée.": "Reject action is 'Do Nothing'. No file actions will be performed.",
        " pour le déplacement des rejets SNR.": " for moving SNR rejects.", # Utilisé en suffixe de message
        "\nCeci s'appliquera aux fichiers marqués pour faible SNR.": "\nThis will apply to files marked for low SNR.", # Utilisé en suffixe de message
        "Application des rejets SNR...": "Applying SNR rejections...",
        "Début application rejets SNR...": "Start applying SNR rejections...",
        "Erreur application actions SNR.": "Error applying SNR actions.",
        "{count} actions SNR appliquées.": "{count} SNR actions applied.",
        "Fin application rejets SNR. {count} actions effectuées.": "End applying SNR rejections. {count} actions performed.",
        "Le fichier log a été mis à jour avec les actions SNR.": "Log file updated with SNR actions.",
        "Échec de l'application des actions SNR.": "Failed to apply SNR actions.",
        "Échec application rejets SNR.": "Failed applying SNR rejections.",
        # --- GUI log messages (analyse_gui_qt) ---  # i18n P0.6
        'gui_no_recommended_images_to_apply': "No recommended images to apply",
        'gui_stack_plan_autoload_failed': "Failed to autoload stack plan: {e}",
        'gui_missing_output_path': "Missing output path — cannot start analysis",
        'gui_using_input_dir_and_log': "Using input dir: {input}, log file: {log}",
        'gui_trail_reject_dir_required': "ERROR: trail reject directory required when moving rejected trail images",
        'gui_snr_reject_dir_required': "ERROR: snr reject directory required when moving rejected SNR images",
        'gui_no_results_stack_plan': "No results available for stack plan",
        'gui_no_images_kept_for_stacking': "No images kept for stacking",
        'gui_stack_plan_created_with_batches': "Stack plan created: {path} with {count} batches",
        'gui_stack_plan_no_results': "Stack plan generation returned no results",
        'gui_stack_plan_create_error': "Error creating stack plan: {e}",
        'gui_stacking_script_prepared_preview': "Stacking script prepared (preview mode)",
        'gui_no_stacking_script_generated': "No stacking script generated",
        'gui_stacking_script_prepare_error': "Error preparing stacking script: {e}",
        'gui_no_log_file_selected': "No log file selected to open",
        'gui_log_file_not_found': "Log file does not exist",
        'gui_open_log_failed': "Open log failed: {e}",
        'gui_stack_plan_window_open_error': "Error opening stack plan window: {e}",
        'gui_stack_plan_export_failed': "Failed to export stack plan: {e}",
        'gui_stacking_script_write_failed': "Failed to write stacking script: {e}",
        'gui_stacking_script_prepare_failed': "Failed to prepare stacking script: {e}",
        'gui_apply_snr_filter_not_implemented': "Apply SNR filter from visualization (not yet implemented)",
        'gui_apply_fwhm_filter_not_implemented': "Apply FWHM filter from visualization (not yet implemented)",
        'gui_visualization_json_decode_error': "ERROR: failed to decode JSON from {path}: {e}",
        'gui_visualization_data_load_error': "ERROR: failed to load visualization data from {path}: {e}",
        'gui_marker_manage_error': "Error managing markers: {e}",
        'gui_no_results_to_visualise': "No results to visualise",
        'gui_results_visualise_error': "Error visualising results: {e}",
        'gui_apply_reco_no_results': "No results available to apply recommendations",
        'gui_apply_reco_no_paths': "No recommended file paths available",
        'gui_apply_reco_error': "Error applying recommendations: {e}",
        'gui_apply_reco_inner_error': "Error in apply recommendations: {e}",
        'gui_marked_good_images': "Marked {count} good images",
        'gui_unmarked_images': "Unmarked {count} images",
        'gui_organizer_no_plan': "Organizer: no plan to apply. Run a scan first.",
        'gui_organizer_error': "Organizer error: {text}",
        'gui_auto_organize_error': "Error in auto organize: {e}",
        'gui_apply_actions_error': "Error applying {action_type} actions: {e}",


# Fin du dictionnaire de traductions
    }
}

# Fallback pour la fonction de traduction
try:
    from zeseestarstacker.i18n import _
except ImportError:
    def _(key, *args, **kwargs):
        return translations.get('fr', {}).get(key, key)

# --- FIN DU FICHIER zone.py ---
